### ISSUE TITLE
User OAuth flat.io

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/community_compose#6]
As a visitor, when I visit '/register' I see a link to authenticate my account with flat.io, and when I click that link and authorize flat.io, I am returned to my '/dashboard' page.

**Comment by reid-andrew** [comment]
Work on this card blocked as of 5/28 - waiting on Flat to provide OAuth access.

**Comment by reid-andrew** [comment]
https://flat.io/developers/docs/api/authentication.html

**Comment by reid-andrew** [comment]
https://flat.io/developers/docs/api/authentication.html
